# Example services.yaml
set_scene_condition_met:
  description: The scene will be able to followed by the specified entities, in case it has the highest priority of all active scenes.
  fields:
    entity_ids:
      description: The entities that will no longer follow the scene.
      required: true
      example: ["light.living_room_ceiling", "light.living_room_tv"]
      selector:
        entity:
          multiple: true
          domain: light
    scene:
      description: The name of the scene whose condition is met.
      required: true
      example: "daylight"
      selector:
        text:
          placeholder: "Enter scene name"

unset_scene_condition_met:
  description: The scene will not be able to be followed by the specified entities.
  fields:
    entity_ids:
      description: The entities that will no longer follow the scene.
      required: true
      example: ["light.living_room_ceiling", "light.living_room_tv"]
      selector:
        entity:
          multiple: true
          domain: light
    scene:
      description: The name of the scene whose condition is no longer met.
      required: true
      example: "daylight"
      selector:
        text:
          placeholder: "Enter scene name"

stop_adjustments:
  description: Stops entities from automatically adjusting their values to follow their scenes.
  fields:
    entity_ids:
      description: The entities that will no longer follow the scene.
      required: true
      example: ["light.living_room_ceiling", "light.living_room_tv"]
      selector:
        entity:
          multiple: true
          domain: light

continue_adjustments:
  description: Continue automatic adjustments of entities, after they were stopped.
  fields:
    entity_ids:
      description: The entities that will no longer follow the scene.
      required: true
      example: ["light.living_room_ceiling", "light.living_room_tv"]
      selector:
        entity:
          multiple: true
          domain: light

set_timeshift:
  description: Sets the timeshift from current time, when the values from the scenes will be calculated for the specified entities.
  fields:
    entity_ids:
      description: The entities that will no longer follow the scene.
      required: true
      example: ["light.living_room_ceiling", "light.living_room_tv"]
      selector:
        entity:
          multiple: true
          domain: light
    timeshift:
      description: The timeshift in minutes.
      required: true
      example: 0
      selector:
        number:
          min: -720
          max: 720
          step: 15
          unit_of_measurement: "minutes"
          mode: slider

shift_timeshift:
  description: Shifts the timeshift from current time, when the values from the scenes will be calculated for the specified entities.
  fields:
    entity_ids:
      description: The entities that will no longer follow the scene.
      required: true
      example: ["light.living_room_ceiling", "light.living_room_tv"]
      selector:
        entity:
          multiple: true
          domain: light
    shift:
      description: The shift to add in minutes.
      required: true
      example: 30
      selector:
        number:
          min: -720
          max: 720
          step: 15
          unit_of_measurement: "minutes"
          mode: slider
